name: executing remote ssh commands using password
uses: appleboy/scp-action@v0.1.7
with:
host: 22.23.33.220
username: ${{ secrets.USERNAME }}
password: ${{ secrets.PASSWORD }}
port: 22
script: whoami
